stages:
  - plan
  - apply
  - file_upload
  - invalidation
  - testing

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  S3_BUCKET_NAME: "juliusaloro.into-cloud.com"
  PLANFILE: "plan.tfplan"
  
# 1st job (check/verify version of terraform used)

terraform_version_check:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - terraform version

# 2nd job (perform terraform plan, output planfile to be used in apply stage)

terraform_plan:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - cd infra/
    - terraform init
    - terraform plan -out=$PLANFILE
    - terraform show $PLANFILE
  artifacts:
    paths:
      - infra/
    untracked: false
    when: on_success
    access: all

# 3rd job (perform terraform build)

terraform_build:
  dependencies:
    - terraform_plan
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: apply
  script:
    - cd infra/
    - terraform apply --auto-approve $PLANFILE
  artifacts:
    paths:
      - infra/
    untracked: false
    when: on_success
    access: all
  
# 4th job (Upload files to s3 [site folder])

file_upload_to_s3:
  image: 
   name: registry.gitlab.com/julius.aloro/my-cloud-resume/amazon/aws-cli:2.22.14
   entrypoint: [""]
  stage: file_upload
  script:
    - aws s3 sync . s3://$S3_BUCKET_NAME/ --delete --exact-timestamps   # sync all contents of site folder recursively
    - echo "Displaying uploaded files..."
    - aws s3 ls s3://$S3_BUCKET_NAME/

# create invalidation
# output cloudfront distribution name and variablize