stages:
  - plan
  - apply
  - file_upload
  - invalidation
  - testing

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  base_url: juliusaloro.into-cloud.com

terraform_apply:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - terraform version
  