stages:
  - plan
  - apply
  - file_upload
  - invalidation
  - testing

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  base_url: "juliusaloro.into-cloud.com"
  planfile: "plan.tfplan"

terraform_version_check:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - terraform version
    - pwd


terraform_plan:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - cd infra/ && mkdir -p plans
    - terraform init
    - terraform plan -out=plans/$planfile
    - terraform show plans/$planfile
  artifacts:
    paths:
      - infra/plans/$planfile
    untracked: false
    when: on_success
    access: all

terraform_build:
  dependencies:
    - terraform_plan
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: apply
  script:
    - terraform apply auto-approve infra/plans/$planfile 

  