stages:
  - Files Checkout
  - Terraform Plan
  - Terraform Apply
  - Files Upload
  - Invalidation
  - Testing

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  base_url: juliusaloro.into-cloud.com

Files Checkout:
  image: registry.gitlab.com/my-cloud-resume/terraform:1.10
  stage: Files Checkout
  script:
    - ls -ltr
  