stages:
  - plan
  - apply
  - file_upload
  - invalidation
  - testing

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  S3_BUCKET_NAME: "juliusaloro.into-cloud.com"
  PLANFILE: "plan.tfplan"

# 1st Stage

terraform_version_check:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - terraform version

# 2nd Stage

terraform_plan:
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: plan
  script:
    - cd infra/
    - terraform init
    - terraform plan -out=$PLANFILE
    - terraform show $PLANFILE
  artifacts:
    paths:
      - infra/
    untracked: false
    when: on_success
    access: all

terraform_build:
  dependencies:
    - terraform_plan
  image:
    name: registry.gitlab.com/julius.aloro/my-cloud-resume/terraform:1.10
    entrypoint: [""]
  stage: apply
  script:
    - cd infra/
    - terraform apply --auto-approve $PLANFILE
  
  # 3rd stage

file_upload_to_s3:
  image: registry.gitlab.com/julius.aloro/my-cloud-resume/amazon/aws-cli:2.22.14
  stage: file_upload
  script:
    - aws help
    - ls -ltr
    